### PR TITLE
Bumped v8.4.0

### PR DESCRIPTION
**Pull request by lauraseidler**
Hey, 

any chance to get the changes from https://github.com/pinojs/hapi-pino/pull/138 out as a release? I've installed from GitHub by commit hash until now, but it's now making some problems, so I'd love to have an npm release :)

Thanks!

### CODE REVIEW

**Comment by mcollina** [comment]
I've added you to npm so you can publish yourself.

**Comment by mcollina** [comment]
Sorry about this, I'm not using this anymore and doing a bad job at releasing it! I hope you don't mind.

**Comment by lauraseidler** [comment]
@mcollina no problem at all, thanks! Anything in particular I need to be aware of?

**Comment by mcollina** [comment]
nope ;), just go ahead and ship it. We usually push version bumps straight to master at publish time, no pr.

**Comment by lauraseidler** [comment]
Cheers! I will merge this one as it's already there, will push directly for the next one :)

Btw, I see that travis builds aren't running anymore (travis-ci.org not a thing anymore) - given that the build is not super complicated, I thought instead of moving to travis-ci.com, GitHub actions might be an option? WDYT?

**Comment by mcollina** [comment]
go for actions!

**Comment by mcollina** [comment]
(also add yourself as a contributor to package.json).

**Pull request merged**
