### PR TITLE
Add support for hapi v18

### PR DESCRIPTION
**Pull request by simoneb**
Addresses #69 in the same way as #70, except for a different test implementation.

### CODE REVIEW

**Comment by simoneb** [comment]
@mcollina to address the coverage issue (which is really not just a coverage issue, if we don't test against hapi 17 we can't guarantee that this change does work against hapi 17), we could enhance the build to run tests against both versions of hapi. Is that something you'd like to do?

**Comment by mcollina** [comment]
I’m thinking we should remove the ternary and just bump the major. It’s simpler to target a single version of a dependency.

**Comment by simoneb** [comment]
@mcollina that's a reasonable option, let me just try an experiment with the build

**Comment by simoneb** [comment]
@mcollina see if you like this https://travis-ci.org/pinojs/hapi-pino/builds/486510355, otherwise we can do as you mentioned

**Comment by simoneb** [comment]
ok, it doesn't address the coverage of the ternary operator but at least we know we're testing against both versions of hapi. let me change the readme to reflect this and then we're good

**Comment by felixheck** [comment]
Awesome, thanks for clarifying 🙏

**Pull request merged**
