### PR TITLE
Bump pino version from 6.0.0 to 7.0.0

### LINKED ISSUE #143: Upgrade to pino@^7.0.0
I have just started to use pino directly in addition to hapi-pino, and noticed that hapi-pino depends on an older version of pino@^6.0.0. Now I have two versions of pino in my node_modules, a situation I’d prefer to avoid.

Would it make sense to upgrade hapi-pino to use pino@^7.0.0?

### PR DESCRIPTION
**Pull request by arty-name**
fixes #143

### CODE REVIEW

**Comment by arty-name** [comment]
Sure! Since Node 16 became LTS recently, I have also added it to the matrix, is that fine?

**Comment by mcollina** [comment]
You need to do https://github.com/pinojs/pino-http/blob/f43143e7cca538ed185ee67affec008a9df840c0/logger.js#L161 as well.


CI is still failing

**Comment by mcollina** [comment]
I think we can drop old API versions.

**Comment by arty-name** [comment]
> I think we can drop old API versions.

What do you mean? Hapi 18 and 19?

**Comment by mcollina** [comment]
Yes, exactly

**Comment by arty-name** [comment]
I removed the older hapi versions, probably the Readme needs to be updated at some point.

The tests fail for me only on Node 16 with this error: `The following leaks were detected:AggregateError, atob, btoa, AbortController, AbortSignal, EventTarget, Event, MessageChannel, MessagePort, MessageEvent, performance`. Do you have an idea about addressing that?

**Comment by mcollina** [comment]
I think you need to update lab.

Can you also update the README?

**Comment by arty-name** [comment]
Indeed, the latest lab version does not have this issue!

**Comment by arty-name** [comment]
I am uncertain about [this comment](https://github.com/pinojs/hapi-pino/pull/144#issuecomment-955183121) though, since it mentions a different package pino-http.

**Comment by mcollina** [comment]
The same block of code must be added here for everything to work.

**Comment by arty-name** [comment]
Do you mean something like this?

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
@lauraseidler can you take a look as well?

This is good to go for me.

**Comment by lauraseidler** [comment]
Sorry for the delay folks - I only have my mobile phone at the moment, but from a quick glance this LGTM.

Should we have a test for those lines added @mcollina ? Not sure if it's testable or why exactly it's needed.

**Comment by mcollina** [comment]
They are testable but likely something we should not really bring here. I'd be ok in landing as is.

**Pull request merged**
