### PR TITLE
implemented hapi-pino as good stream for benchmarks

### PR DESCRIPTION
**Pull request by yonjah**
This is not intended to be merged upstream it's
just very simple implementation of hapi-pino as good stream for benchmarking.

### CODE REVIEW

**Comment by mcollina** [comment]
I've seen that with all of those, the CPU keep spinning _after_ the benchmarks ends, for some seconds.
It seems a lot of the logging activity is postponed, either in the stream, or in good or in pino. 
The end result is that logging is not the bottleneck in hapi.

**Comment by mcollina** [comment]
I finally understood what was going on, and it was https://github.com/hapijs/hapi/issues/3347.
That is now fixed in hapi v16.
I think good-pino is a good module to have, would you like to publish it? From my tests is 10% slower than hapi-pino, but your mileage may vary in real world apps, and it is definitely worth having!

**Comment by yonjah** [comment]
@mcollina  can you publish your benchmarks results ?
I haven't tested with hapi v16 yet but with previous version I couldn't reproduce the numbers you mentioned. so I wanna be sure I'm not missing anything.

I think good-pino needs a bit more work to be usable (mostly adding more formatters for all possible log events ) but since I'm still considering pino I don't think it will be a good idea to maintain this module at the moment.
In the future if I decide to use pino and do it as a good stream I'll probably publish and maintain the module (unless anyone else will do by then).

**Comment by mcollina** [comment]
Hapi v15 has a **sever** performance regression and it should not be used.

Server: `node benchmarks/good.js > /dev/null`

```
$ autocannon -c 100 -d 10 -p 10 localhost:3000
Running 10s test @ http://localhost:3000
100 connections with 10 pipelining factor

Stat         Avg       Stdev   Max
Latency (ms) 59.9      180.69  896
Req/Sec      1616      167.15  1751
Bytes/Sec    355.94 kB 36.1 kB 393.21 kB

16k requests in 10s, 3.57 MB read
```

Server: `node benchmarks/hapi-pino.js > /dev/null`

```
$ autocannon -c 100 -d 10 -p 10 localhost:3000
Running 10s test @ http://localhost:3000
100 connections with 10 pipelining factor

Stat         Avg       Stdev    Max
Latency (ms) 49.37     149.36   1245
Req/Sec      1976.3    199.21   2155
Bytes/Sec    437.45 kB 45.05 kB 491.52 kB

20k requests in 10s, 4.37 MB read
```

Server: `node example-stream.js > /dev/null`

```
$ autocannon -c 100 -d 10 -p 10 localhost:3000
Running 10s test @ http://localhost:3000
100 connections with 10 pipelining factor

Stat         Avg       Stdev    Max
Latency (ms) 53.5      162.55   1005
Req/Sec      1818      159.85   1952
Bytes/Sec    399.77 kB 33.94 kB 442.37 kB

18k requests in 10s, 4.02 MB read
```

**Comment by yonjah** [comment]
Ok.
I'm getting roughly the same results with hapi v16.

**Comment by mcollina** [comment]
Closing as we will not be pursuing this direction. `good-pino` should be a different module if you would like to release this separately.

**Pull request closed without merging**
