### PR TITLE
feat: Filter out logs based on event tags

### PR DESCRIPTION
**Pull request by adarshkr**
Added a few feature - which enables us to filter the logs bases event tags.

### CODE REVIEW

**Comment by mcollina** [comment]
CI is failing, can you take a look?

**Comment by adarshkr** [comment]
> CI is failing, can you take a look?

Screenshot 2020-08-14 at 10 14 55 AM

The build was successful. Just code coverage is dropped by 0.07% because of if check.

**Comment by mcollina** [comment]
> The build was successful. Just code coverage is dropped by 0.07% because of if check.

No worries

**Comment by mcollina** [comment]
Can you rebase? This now conflicts with master.

**Comment by krlilly** [comment]
> Can you rebase? This now conflicts with master.

Done. Rebased

**Comment by adarshkr** [comment]
Hi @mcollina are this changes published ?

**Pull request merged**
